name: Docker Test on Push

on:
  push:
    branches:
      - main
      - testing
  pull_request:
    branches:
      - main

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t simple-hello-test .

      - name: Run tests in Docker
        run: docker run --rm simple-hello-test
