name: On Push Workflow

on:
  push:
    branches:
      - main
      - development
      - production
      - testing



jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hellon
        run: echo "🚀 Code was pushed! Hello from GitHub Actions"
